



directory RT_VERSION,versions

resource versions,\
1,LANG_ENGLISH,version_info

versioninfo version_info,VOS__WINDOWS32,VFT_APP,VFT2_UNKNOWN,\
 LANG_ENGLISH+SUBLANG_DEFAULT,0,\
 'FileDescription','Screen Recorder APP 1.1.0.2',\
 'LegalCopyright','© 2011 O Applications',\
 'FileVersion','1.1.0.2',\
 'ProductName','Screen Recorder',\
 'ProductVersion','1.1.0.2',\
 'OriginalFilename','s_recorder.exe'